//! Copyright (c) Alexander Matzen. All rights reserved.
//! Licensed under the MIT license.
//!
//! Mouse cursor store: kernel-bundled cursors plus one filesystem-loaded
//! custom cursor.
//!
//! - Bundled cursors come from `cursors/` via `cursor_data.rs` (generated by
//!   `tools/convert_cursor.py`; every common image type in that dir is
//!   bundled automatically).
//! - The Settings app can additionally load any `.png`/`.jpg`/`.jpeg`/`.bmp`
//!   /`.gif` from `/cursors` on the filesystem (same decoders as wallpaper,
//!   but with tighter cursor caps via `wallpaper::decode_cursor`).
//! - Hotspot (click tip): bundled hotspot from the `<stem>.hotspot` sidecar
//!   (default top-left `0,0`); filesystem cursors default to `0,0` unless a
//!   sibling `<name>.hotspot` file with `x,y` is present.
//! - Selection persists as `cursor=<name-or-path>` in `/config/settings.cfg`
//!   (see `wallpaper::parse_settings` / `format_settings`).

use super::cursor_data::{BUNDLED_CURSORS, DEFAULT_CURSOR_INDEX};
use super::wallpaper::{self, MAX_CURSOR_DIM};
use alloc::string::String;
use alloc::vec::Vec;
use spin::Mutex;

/// Directory the Settings UI browses for filesystem cursors.
pub const CURSOR_DIR: &str = "/cursors";
/// Max cursor dimension the renderer accepts (matches build-time clamp).
pub const CURSOR_MAX_DIM: u32 = MAX_CURSOR_DIM;

/// Name of the default cursor (index 0 of the bundled table).
pub fn default_name() -> &'static str {
    BUNDLED_CURSORS[DEFAULT_CURSOR_INDEX].name
}

struct CustomCursor {
    name: String,
    rgba: Vec<u8>,
    w: u32,
    h: u32,
    hx: u32,
    hy: u32,
}

struct CursorState {
    bundled_idx: usize,
    custom: Option<CustomCursor>,
}

impl CursorState {
    const fn new() -> Self {
        Self {
            bundled_idx: DEFAULT_CURSOR_INDEX,
            custom: None,
        }
    }
}

static CURSOR: Mutex<CursorState> = Mutex::new(CursorState::new());

/// Parse a `<name>.hotspot` sidecar (`x,y`, e.g. `3,1`). `None` on any
/// malformed input (caller falls back to top-left).
pub fn parse_hotspot(text: &str) -> Option<(u32, u32)> {
    let t = text.trim().replace(';', ",");
    let mut parts = t.split(',');
    let x: u32 = parts.next()?.trim().parse().ok()?;
    let y: u32 = parts.next()?.trim().parse().ok()?;
    if parts.next().is_some() {
        return None;
    }
    if x > CURSOR_MAX_DIM || y > CURSOR_MAX_DIM {
        return None;
    }
    Some((x, y))
}

/// Number of kernel-bundled cursors.
pub fn bundled_count() -> usize {
    BUNDLED_CURSORS.len()
}

/// Case-insensitive bundled lookup. Accepts bare names (`arrow`), names
/// with an image extension (`arrow.png`), and full paths
/// (`/cursors/arrow.png`).
pub fn find_bundled(name: &str) -> Option<usize> {
    let mut t = name.trim();
    if let Some(slash) = t.rfind('/') {
        t = &t[slash + 1..];
    }
    let t = t.trim();
    if t.is_empty() {
        return None;
    }
    // Strip one image extension for the comparison.
    let lower = t.to_ascii_lowercase();
    let bare = ["png", "jpg", "jpeg", "bmp", "gif", "webp", "ico", "cur"]
        .iter()
        .find_map(|ext| lower.strip_suffix(ext).and_then(|s| s.strip_suffix('.')))
        .unwrap_or(&lower);
    BUNDLED_CURSORS.iter().position(|c| {
        c.name.to_ascii_lowercase() == bare || c.name.to_ascii_lowercase() == lower
    })
}

/// Select a bundled cursor (clears any filesystem custom cursor).
/// Returns false when `idx` is out of range (selection unchanged).
pub fn select_bundled(idx: usize) -> bool {
    if idx >= BUNDLED_CURSORS.len() {
        return false;
    }
    let mut st = CURSOR.lock();
    st.bundled_idx = idx;
    st.custom = None;
    true
}

/// Currently selected bundled index, or `None` while a filesystem cursor
/// is active.
pub fn selected_index() -> Option<usize> {
    let st = CURSOR.lock();
    if st.custom.is_some() {
        None
    } else {
        Some(st.bundled_idx.min(BUNDLED_CURSORS.len().saturating_sub(1)))
    }
}

/// Install filesystem bytes as the active cursor. Decodes with cursor caps
/// (max 512 KiB, max 128x128). Hotspot is clamped inside the image.
pub fn set_custom_bytes(
    bytes: &[u8],
    name: &str,
    hx: u32,
    hy: u32,
) -> Result<(u32, u32), &'static str> {
    let img = wallpaper::decode_cursor(bytes)?;
    let hx = hx.min(img.w.saturating_sub(1));
    let hy = hy.min(img.h.saturating_sub(1));
    let (w, h) = (img.w, img.h);
    let mut st = CURSOR.lock();
    st.custom = Some(CustomCursor {
        name: capped_name(name),
        rgba: img.rgba,
        w,
        h,
        hx,
        hy,
    });
    Ok((w, h))
}

/// Reset to the default cursor (bundled default, no custom).
pub fn select_default() {
    let mut st = CURSOR.lock();
    st.bundled_idx = DEFAULT_CURSOR_INDEX;
    st.custom = None;
}

fn capped_name(name: &str) -> String {
    let t = name.trim();
    let mut s = String::from(t);
    if s.len() > 128 {
        s.truncate(128);
    }
    s
}

/// Persistence value: `""` for the default cursor (keeps old settings files
/// clean), otherwise the bundled name or the filesystem path.
pub fn current_name() -> String {
    let st = CURSOR.lock();
    if let Some(c) = st.custom.as_ref() {
        return c.name.clone();
    }
    if st.bundled_idx == DEFAULT_CURSOR_INDEX {
        return String::new();
    }
    String::from(
        BUNDLED_CURSORS
            .get(st.bundled_idx)
            .map(|c| c.name)
            .unwrap_or(""),
    )
}

/// Human-readable status (`name WxH hotspot x,y`, or `name (custom) ...`).
pub fn describe() -> String {
    let st = CURSOR.lock();
    if let Some(c) = st.custom.as_ref() {
        return alloc::format!(
            "{} (custom) {}x{} hotspot {},{}",
            c.name,
            c.w,
            c.h,
            c.hx,
            c.hy
        );
    }
    let idx = st.bundled_idx.min(BUNDLED_CURSORS.len().saturating_sub(1));
    let c = &BUNDLED_CURSORS[idx];
    alloc::format!("{} {}x{} hotspot {},{}", c.name, c.w, c.h, c.hotspot_x, c.hotspot_y)
}

/// Run `f` with the current cursor bitmap. The lock is held across the call
/// (same discipline as `wallpaper::paint_cached_fullscreen`: wallpaper ->
/// framebuffer, never reversed).
pub fn with_current<F, R>(f: F) -> R
where
    F: FnOnce(usize, usize, usize, usize, &[u8]) -> R,
{
    let st = CURSOR.lock();
    if let Some(c) = st.custom.as_ref() {
        return f(c.w as usize, c.h as usize, c.hx as usize, c.hy as usize, &c.rgba);
    }
    let idx = st.bundled_idx.min(BUNDLED_CURSORS.len().saturating_sub(1));
    let c = &BUNDLED_CURSORS[idx];
    f(c.w, c.h, c.hotspot_x, c.hotspot_y, c.rgba)
}

/// Largest bundled cursor dimension (dirty-rect upper bound so switching to
/// a smaller cursor still repaints the old area). Custom cursors are capped
/// at 128px, so the bound covers them too.
pub fn max_bundled_dim() -> usize {
    let mut m = 32usize;
    for c in BUNDLED_CURSORS {
        m = m.max(c.w).max(c.h);
    }
    m.max(CURSOR_MAX_DIM as usize)
}

/// A decoded copy of the active cursor (for Settings previews).
pub fn current_image() -> wallpaper::DecodedImage {
    let st = CURSOR.lock();
    if let Some(c) = st.custom.as_ref() {
        return wallpaper::DecodedImage {
            rgba: c.rgba.clone(),
            w: c.w,
            h: c.h,
        };
    }
    let idx = st.bundled_idx.min(BUNDLED_CURSORS.len().saturating_sub(1));
    let c = &BUNDLED_CURSORS[idx];
    wallpaper::DecodedImage {
        rgba: c.rgba.to_vec(),
        w: c.w as u32,
        h: c.h as u32,
    }
}

/// Preview RGBA for the Settings window (uses the wallpaper Fit helper).
pub fn preview_rgba(max_w: u32, max_h: u32) -> Option<(Vec<u8>, u32, u32)> {
    let img = current_image();
    wallpaper::make_preview(&img, max_w, max_h, 0x14181d)
}

#[cfg(test)]
mod tests {
    use super::{find_bundled, parse_hotspot};

    #[test]
    fn hotspot_parses() {
        assert_eq!(parse_hotspot("3,1"), Some((3, 1)));
        assert_eq!(parse_hotspot(" 5 ; 6 "), Some((5, 6)));
        assert_eq!(parse_hotspot("0,0"), Some((0, 0)));
        assert_eq!(parse_hotspot(""), None);
        assert_eq!(parse_hotspot("3"), None);
        assert_eq!(parse_hotspot("3,1,2"), None);
        assert_eq!(parse_hotspot("x,y"), None);
        assert_eq!(parse_hotspot("999,999"), None);
    }

    #[test]
    fn bundled_lookup() {
        // Generated table always contains the default cursor.
        assert!(super::bundled_count() >= 1);
        assert_eq!(super::default_name(), "mfk-default");
        assert_eq!(find_bundled("mfk-default"), Some(0));
        assert_eq!(find_bundled("MFK-DEFAULT.PNG"), Some(0));
        assert_eq!(find_bundled("/cursors/mfk-default.png"), Some(0));
        assert_eq!(find_bundled("no-such-cursor"), None);
        assert_eq!(find_bundled(""), None);
    }

    #[test]
    fn select_roundtrip() {
        assert!(super::select_bundled(0));
        assert_eq!(super::selected_index(), Some(0));
        assert!(!super::select_bundled(9999));
        assert_eq!(super::selected_index(), Some(0));
    }
}
