#!/usr/bin/env python3
"""Convert cursors/mfk-default.png to kernel-embeddable RGBA bytes.

Regenerate with:  python3 tools/convert_cursor.py
Output:           kernel/src/desktop/cursor_data.rs  (checked in)

The kernel is no_std, so instead of a PNG decoder it includes these raw
bytes (see kernel/src/desktop/mod.rs cursor blit).
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "cursors" / "mfk-default.png"
DST = ROOT / "kernel" / "src" / "desktop" / "cursor_data.rs"

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow required: pip install pillow")


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    w, h = im.size
    px = list(im.get_flattened_data())
    # Keep the hotspot on the original arrow tip. The outline in the source
    # bitmap can extend above/left of the opaque cursor body.
    hotspot = (3, 1)
    vals = []
    for r, g, b, a in px:
        vals.extend((str(r), str(g), str(b), str(a)))
    body = ", ".join(vals)
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(
        "//! Generated by tools/convert_cursor.py - do not edit by hand.\n"
        f"//! Source: cursors/mfk-default.png ({w}x{h} RGBA).\n"
        "//! Regenerate with: python3 tools/convert_cursor.py\n"
        "\n"
        f"pub const CURSOR_W: usize = {w};\n"
        f"pub const CURSOR_H: usize = {h};\n"
        f"pub const CURSOR_HOTSPOT_X: usize = {hotspot[0]};\n"
        f"pub const CURSOR_HOTSPOT_Y: usize = {hotspot[1]};\n"
        "/// Row-major RGBA bytes (alpha: 0 = transparent).\n"
        f"pub const CURSOR_RGBA: [u8; {w * h * 4}] = [{body}];\n",
        encoding="utf-8",
    )
    print(f"wrote {DST} ({w}x{h}, hotspot {hotspot[0]},{hotspot[1]})")


if __name__ == "__main__":
    main()
