#!/usr/bin/env python3
"""Bundle every cursor image in cursors/ into kernel-embeddable RGBA bytes.

Regenerate with:  python3 tools/convert_cursor.py
Output:           kernel/src/desktop/cursor_data.rs  (checked in)

Drop any common image file into cursors/ (.png .jpg .jpeg .bmp .gif .webp
.ico .cur .tif .tiff) and re-run this script: each file becomes one
bundled cursor. Pillow handles the decoding at build time, so the kernel
itself only needs its PNG/JPG/BMP/GIF decoders at runtime (for /cursors
files on the filesystem).

Hotspot (click tip): `<stem>.hotspot` sidecar with `x,y` (e.g. `3,1`).
No sidecar means top-left (0,0), except `mfk-default` which keeps its
historical arrow-tip hotspot (3,1). Images larger than 128px are
downscaled (aspect-preserving) to fit the kernel cursor cap.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "cursors"
DST = ROOT / "kernel" / "src" / "desktop" / "cursor_data.rs"

EXTS = {
    ".png", ".jpg", ".jpeg", ".bmp", ".gif",
    ".webp", ".ico", ".cur", ".tif", ".tiff",
}
MAX_DIM = 128
# mfk-default keeps its historical arrow-tip hotspot when no sidecar exists.
LEGACY_HOTSPOTS = {"mfk-default": (3, 1)}

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow required: pip install pillow")


def sanitize(name: str) -> str:
    s = re.sub(r"[^0-9A-Za-z]+", "_", name).strip("_").upper()
    if not s or s[0].isdigit():
        s = "C_" + s
    return s


def read_hotspot(path: Path, stem: str) -> tuple:
    sidecar = path.with_suffix(".hotspot")
    if sidecar.is_file():
        try:
            x, y = sidecar.read_text(encoding="utf-8").strip().replace(";", ",").split(",")[:2]
            return (max(0, int(x.strip())), max(0, int(y.strip())))
        except Exception as e:
            sys.exit(f"bad hotspot file {sidecar}: {e} (want 'x,y')")
    if stem.lower() in LEGACY_HOTSPOTS:
        return LEGACY_HOTSPOTS[stem.lower()]
    return (0, 0)


def load_rgba(path: Path):
    im = Image.open(path)
    # Animated files (GIF/WebP): bundle the first frame.
    try:
        im.seek(0)
    except Exception:
        pass
    im = im.convert("RGBA")
    w, h = im.size
    if max(w, h) > MAX_DIM:
        scale = MAX_DIM / max(w, h)
        im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
        w, h = im.size
    # get_flattened_data() yields one (r,g,b,a) tuple per pixel.
    return w, h, list(im.get_flattened_data())


def main() -> None:
    files = sorted(
        (p for p in SRC_DIR.iterdir() if p.is_file() and p.suffix.lower() in EXTS),
        key=lambda p: p.name.lower(),
    )
    if not files:
        sys.exit(f"no cursor images in {SRC_DIR} (need one of {sorted(EXTS)})")
    entries = []
    for path in files:
        stem = path.stem
        w, h, px = load_rgba(path)
        hx, hy = read_hotspot(path, stem)
        hx, hy = min(hx, max(0, w - 1)), min(hy, max(0, h - 1))
        entries.append((stem, sanitize(stem), w, h, hx, hy, px, path.name))
    # Default cursor: mfk-default first when present, else alphabetical first.
    entries.sort(key=lambda e: (0 if e[0].lower() == "mfk-default" else 1, e[0].lower()))

    lines = []
    lines.append("//! Generated by tools/convert_cursor.py - do not edit by hand.")
    for stem, _tag, w, h, hx, hy, _px, fname in entries:
        lines.append(f"//! Source: cursors/{fname} ({w}x{h} RGBA, hotspot {hx},{hy}).")
    lines.append("//! Every image in cursors/ is bundled; re-run the script after adding files.")
    lines.append("//! Regenerate with: python3 tools/convert_cursor.py")
    lines.append("")
    lines.append("/// One kernel-bundled mouse cursor.")
    lines.append("pub struct BundledCursor {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub w: usize,")
    lines.append("    pub h: usize,")
    lines.append("    pub hotspot_x: usize,")
    lines.append("    pub hotspot_y: usize,")
    lines.append("    pub rgba: &'static [u8],")
    lines.append("}")
    lines.append("")
    for stem, tag, w, h, _hx, _hy, px, _fname in entries:
        flat = []
        for r, g, b, a in px:
            flat.extend((str(r), str(g), str(b), str(a)))
        body = ", ".join(flat)
        lines.append("/// Row-major RGBA bytes (alpha: 0 = transparent).")
        lines.append(f"pub const CURSOR_{tag}_RGBA: [u8; {w * h * 4}] = [{body}];")
        lines.append("")
    lines.append("/// All cursors bundled from `cursors/` (index 0 = default).")
    lines.append(
        f"pub const BUNDLED_CURSORS: [BundledCursor; {len(entries)}] = ["
    )
    for stem, tag, w, h, hx, hy, _px, _fname in entries:
        lines.append("    BundledCursor {")
        lines.append(f'        name: "{stem}",')
        lines.append(f"        w: {w},")
        lines.append(f"        h: {h},")
        lines.append(f"        hotspot_x: {hx},")
        lines.append(f"        hotspot_y: {hy},")
        lines.append(f"        rgba: &CURSOR_{tag}_RGBA,")
        lines.append("    },")
    lines.append("];")
    lines.append("")
    lines.append("/// Index of the default cursor in [`BUNDLED_CURSORS`].")
    lines.append("pub const DEFAULT_CURSOR_INDEX: usize = 0;")
    lines.append("")
    # Legacy single-cursor aliases (default cursor) for compatibility.
    # (Kept for external refs; allow dead code since the desktop now reads
    # the bundled table through cursor.rs.)
    d = entries[0]
    lines.append("// Legacy single-cursor aliases (default cursor) for compatibility.")
    for doc, decl in [
        ("width of the default cursor.", f"pub const CURSOR_W: usize = {d[2]};"),
        ("height of the default cursor.", f"pub const CURSOR_H: usize = {d[3]};"),
        ("hotspot x of the default cursor.", f"pub const CURSOR_HOTSPOT_X: usize = {d[4]};"),
        ("hotspot y of the default cursor.", f"pub const CURSOR_HOTSPOT_Y: usize = {d[5]};"),
        (
            "RGBA of the default cursor.",
            f"pub const CURSOR_RGBA: [u8; {d[2] * d[3] * 4}] = CURSOR_{d[1]}_RGBA;",
        ),
    ]:
        lines.append(f"/// Legacy alias: {doc}")
        lines.append("#[allow(dead_code)]")
        lines.append(decl)
    lines.append("")
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines), encoding="utf-8")
    for stem, _tag, w, h, hx, hy, _px, fname in entries:
        print(f"bundled {fname} -> {stem} ({w}x{h}, hotspot {hx},{hy})")
    print(f"wrote {DST} ({len(entries)} cursors)")


if __name__ == "__main__":
    main()
